const city = [
  { value: 'Amsterdam - Netherlands' },
  { value: 'Ankara -  Turkey' },
  { value: 'Athens - Greece' },
  { value: 'Atlantic City - USA' },
  { value: 'Baltimore - USA' },
  { value: 'Bangkok - Thailand' },
  { value: 'Barcelona - Spain' },
  { value: 'Beijing - China' },
  { value: 'Berlin - Germany' },
  { value: 'Berne - Switzerland' },
  { value: 'Brussels - Belgium' },
  { value: 'Budapest - Hungary' },
  { value: 'Buenos Aires - Argentina' },
  { value: 'Cairo - Egypt' },
  { value: 'Canberra - Australia' },
  { value: 'Cannes -  France' },
  { value: 'Cape Town  - South Africa' },
  { value: 'Chicago - USA' },
  { value: 'Cologne - Germany' },
  { value: 'Copenhagen - Denmark' },
  { value: 'Damascus - Syria' },
  { value: 'Delhi - India' },
  { value: 'Dubai City - United Arab Emirates' },
  { value: 'Dublin - Ireland' },
  { value: 'Florence - Italy' },
  { value: 'Genève - Switzerland' },
  { value: 'Hague - Netherlands' },
  { value: 'Ha Noi -  Viet Nam' },
  { value: 'Havana -  Cuba' },
  { value: 'Helsinki - Finland' },
  { value: 'Hong Kong - China' },
  { value: 'Honolulu - USA' },
  { value: 'Istanbul - Turkey' },
  { value: 'Jakarta - Indonesia' },
  { value: 'Kansas City - USA' },
  { value: 'Kathmandu - Nepal' },
  { value: 'Kuala Lumpur - Malaysia' },
  { value: 'Lisbon - Portugal' },
  { value: 'London - United Kingdom' },
  { value: 'Los Angeles - USA' },
  { value: 'Luxembourg - Luxembourg' },
  { value: 'Madrid - Spain' },
  { value: 'Manila - Philippines' },
  { value: 'Melbourne - Australia' },
  { value: 'Mexico City - Mexico' },
  { value: 'Milan - Italy' },
  { value: 'Montreal - Canada' },
  { value: 'Moscow - Russia' },
  { value: 'Mumbai -  India' },
  { value: 'Munich - Germany' },
  { value: 'Nazareth - Israel' },
  { value: 'New York - USA' },
  { value: 'Nice - France' },
  { value: 'Osaka - Japan' },
  { value: 'Ottawa - Canada' },
  { value: 'Oslo - Norway' },
  { value: 'Paris - France' },
  { value: 'Philadelphia - USA' },
  { value: 'Phnom Penh - Cambodia' },
  { value: 'Prague - Czech Republic' },
  { value: 'Quito - Bolivia' },
  { value: 'Reykjavik - Iceland' },
  { value: 'Rio de Janeiro - Brazil' },
  { value: 'San Francisco - USA' },
  { value: 'Santiago - Chile' },
  { value: 'São Paulo - Brazil' },
  { value: 'Shanghai - China' },
  { value: 'Singapore City - Singapore' },
  { value: 'Stockholm - Sweden' },
  { value: 'Saint Petersburg - Russia' },
  { value: 'Seoul - South Korea' },
  { value: 'Sydney - Australia' },
  { value: 'Taipei - Taiwan' },
  { value: 'Tokyo - Japan' },
  { value: 'Toronto - Canada' },
  { value: 'Venice - Italy' },
  { value: 'Vienna - Austria' },
  { value: 'Washington - USA' },
  { value: 'Zürich - Switzerland' },
];

export default city;
