const city = [
  { value: 'Vienna', label: 'Vienna' },
  { value: 'Brussels', label: 'Brussels' },
  { value: 'Prague', label: 'Prague' },
  { value: 'Copenhagen', label: 'Copenhagen' },
  { value: 'Minsk', label: 'Minsk' },
  { value: 'Helsinki', label: 'Helsinki' },
  { value: 'Budapest', label: 'Budapest' },
  { value: 'Paris', label: 'Paris' },
  { value: 'Berlin', label: 'Berlin' },
  { value: 'Athens', label: 'Athens' },
  { value: 'Dublin', label: 'Dublin' },
  { value: 'Rome', label: 'Rome' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Monaco', label: 'Monaco' },
  { value: 'Amsterdam', label: 'Amsterdam' },
  { value: 'Oslo', label: 'Oslo' },
  { value: 'Warsaw', label: 'Warsaw' },
  { value: 'Lisbon', label: 'Lisbon' },
  { value: 'Moscow', label: 'Moscow' },
  { value: 'Madrid', label: 'Madrid' },
  { value: 'Stockholm', label: 'Stockholm' },
  { value: 'London', label: 'London' },
  { value: 'Kyiv', label: 'Kyiv' },
  { value: 'Vatican City', label: 'Vatican City' },
  { value: 'Brasilia', label: 'Brasilia' },
  { value: 'Ottawa', label: 'Ottawa' },
  { value: 'Buenos Aires', label: 'Buenos Aires' },
  { value: 'Bogota', label: 'Bogota' },
  { value: 'San José', label: 'San José' },
  { value: 'Havana', label: 'Havana' },
  { value: 'Kingston', label: 'Kingston' },
  { value: 'Washington, D.C.', label: 'Washington, D.C.' },
  { value: 'NewYork', label: 'NewYork' },
  { value: 'SanFrancisco', label: 'SanFrancisco' },
  { value: 'Los Angeles', label: 'Los Angeles' },
  { value: 'Beijing', label: 'Beijing' },
  { value: 'Guangzhou', label: 'Guangzhou' },
  { value: 'Shanghai', label: 'Shanghai' },
  { value: 'New Delhi', label: 'New Delhi' },
  { value: 'Hong Kong', label: 'Hong Kong' },
  { value: 'Tehran', label: 'Tehran' },
  { value: 'Tokyo', label: 'Tokyo' },
  { value: 'Doha', label: 'Doha' },
  { value: 'Riyadh', label: 'Riyadh' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Seoul', label: 'Seoul' },
  { value: 'Taipei', label: 'Taipei' },
  { value: 'Bangkok', label: 'Bangkok' },
  { value: 'Abu Dhabi', label: 'Abu Dhabi' },
  { value: 'Addis Ababa', label: 'Addis Ababa' },
  { value: 'Nairobi', label: 'Nairobi' },
  { value: 'Pretoria', label: 'Pretoria' },
  { value: 'Kigali', label: 'Kigali' },
  { value: 'Cairo', label: 'Cairo' },
  { value: 'Rabat', label: 'Rabat' },
];

export default city;
